sudo: false
services:
  - 'docker'
script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t sermilrod/go-echoserver:$TRAVIS_PULL_REQUEST_SHA .
  - docker push sermilrod/go-echoserver:$TRAVIS_PULL_REQUEST_SHA
